### ISSUE TITLE
Automatically move issue to `In Progress` column on assigning

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#200]
We need a little automation to GitHub Projects.

When I assign somebody to issue in `Onboarding`/`Ready to take`, the issue should move to `In Progress` column.

The workflow should look like:

```yml
name: Move Assigned Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move:
    name: Move
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
      # Some way to move issue
```

Note, that we are using `Project (beta)` (also Project V2), and not old classic projects. So many solutions from Google/ChatGPT will not work.

1. Create a new your own repo.
2. Create a project V2 there with `New` and `In Progress` columns.
3. Add workflow.
4. Create some task and put it to `New`.
5. Assign yourself to `In Progress`
6. Check that everything works in GitHub Actions and project view.
7. Create PR to Slow Reader.
8. Use `secrets.PROJECTS_MOVE` with token, but explain in PR what permissions this token need. We are using new `fine-tuning` tokens, not classic.
